export const CALL_FETCH_CATEGORIES_API = 'CALL_FETCH_CATEGORIES_API';
export const CALL_FETCH_PRODUCTS_API = 'CALL_FETCH_PRODUCTS_API';
export const CALL_FETCH_PRODUCTS_BY_CATEGORY_API =
  'CALL_FETCH_PRODUCTS_BY_CATEGORY_API' as const;
